# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email                     : "info@meinestadt.de"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username          : "meinestadt_de"
github_username           : "robert-ms"
minimal_mistakes_skin     : default
search: true

locale                    : "de-DE"
title                     : "meinestadt.de Tech-Blog"
title_separator           : "|"
subtitle                  : "Great people's work"
name                      : "meinestadt.de GmbH"
description               : "An amazing tech blog."
url                       : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                   : # the subpath of your site, e.g. "/blog"
repository                : "robert-ms/ms-techblog" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
masthead_title            : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs             : false # true, false (default)
words_per_minute          : 200

teaser                    : "/assets/images/500x300.jpg"
logo                      : "/assets/images/88x88.png"

# Build settings
markdown                  : kramdown
remote_theme              : mmistakes/minimal-mistakes
# Outputting
permalink                 : /:categories/:title/
paginate                  : 5 # amount of posts to show
paginate_path             : /page:num/
timezone                  : "Europe/Berlin" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "meinestadt.de GmbH"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://meinestadt.de/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/meinestadt_de/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/robert-ms/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/meinestadt.de/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/meinestadt_de/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/robert-ms/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/meinestadt.de/"
    - label: "Impressum"
      icon: "fa-file-alt"
      url: "https://www.meinestadt.de/impressum/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
